// V14 — five independent report renderers rebuilt from the supplied educational references.
(function(){
'use strict';
const F=document.querySelector('#reportForm'); if(!F)return;
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const V=n=>String(F.elements[n]?.value||'').trim();
const H=n=>!!V(n); const N=n=>Number(V(n))||0;
const E=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const L=s=>String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
const P=()=>typeof images!=='undefined'&&Array.isArray(images)?images:[];
const title=()=>V('title')||'عنوان التقرير';
const type=()=>V('reportType')||'تقرير توثيق';
const logo=()=>'<img class="v14-moe" src="./moe-logo-official.png?v=140" alt="وزارة التعليم">';
const identity=()=>`<div class="v14-id">${logo()}<div>${H('authority')?`<small>${E(V('authority'))}</small>`:''}${H('school')?`<b>${E(V('school'))}</b>`:''}</div></div>`;
const person=()=>H('executor')||H('jobTitle')?`<div class="v14-person">${H('jobTitle')?`<small>${E(V('jobTitle'))}</small>`:''}${H('executor')?`<b>${E(V('executor'))}</b>`:''}</div>`:'';
const brand=()=>'<span class="v14-brand">توثيق</span>';
const facts=()=>[['date','التاريخ','◷'],['duration','المدة','◴'],['audience','الفئة المستهدفة','◉'],['location','المكان','⌖'],['department','القسم / الوحدة','▣']].filter(([k])=>H(k)).map(([k,l,i])=>({k,l,i,v:V(k)}));
function metrics(){const a=[];[['beneficiaries','المستفيدون',''],['attendance','نسبة الحضور','%'],['satisfaction','نسبة الرضا','%'],['activities','الأنشطة',''],['students','الطلاب',''],['femaleStudents','الطالبات',''],['teachers','المعلمون',''],['femaleTeachers','المعلمات','']].forEach(([k,l,u])=>{if(H(k)&&N(k)>0)a.push({l,v:N(k),u,type:u==='%'?'percent':'count'})});if(N('target')>0&&N('achieved')>0)a.unshift({l:'تحقق المستهدف',v:Math.min(100,Math.round(N('achieved')/N('target')*100)),u:'%',type:'percent'});else{if(N('target')>0)a.push({l:'المستهدف',v:N('target'),u:'',type:'count'});if(N('achieved')>0)a.push({l:'المتحقق',v:N('achieved'),u:'',type:'count'})}qa('.metric-name').forEach((x,i)=>{const v=Number(qa('.metric-value')[i]?.value)||0;if(x.value.trim()&&v>0)a.push({l:x.value.trim(),v,u:'',type:'count'})});return a.slice(0,8)}
const para=n=>H(n)?`<p>${E(V(n)).replace(/\n/g,'<br>')}</p>`:'';
const list=n=>H(n)?L(V(n)).map((x,i)=>`<div class="v14-item"><i>${String(i+1).padStart(2,'0')}</i><span>${E(x)}</span></div>`).join(''):'';
function factbar(cls=''){const a=facts();return a.length?`<div class="v14-facts ${cls}">${a.map(x=>`<div><span>${x.i}</span><small>${x.l}</small><b>${E(x.v)}</b></div>`).join('')}</div>`:''}
function metricRow(cls=''){const a=metrics();return a.length?`<div class="v14-metrics ${cls}">${a.map(x=>x.type==='percent'?`<div class="v14-ring" style="--p:${Math.min(100,x.v)}"><i><b>${x.v}%</b></i><small>${E(x.l)}</small></div>`:`<div class="v14-number"><b>${x.v}</b><small>${E(x.l)}</small></div>`).join('')}</div>`:''}
function photos(cls=''){const a=P().slice(0,10);if(!a.length)return'';return `<div class="v14-photos ${cls} n${a.length}">${a.map((x,i)=>`<figure><img src="${x.src}" alt="شاهد ${i+1}">${x.caption?`<figcaption>${E(x.caption)}</figcaption>`:''}</figure>`).join('')}</div>`}
const approval=()=>H('approver')?`<div class="v14-approval"><small>الاعتماد</small><b>${E(V('approver'))}</b></div>`:'';
const footer=()=>`<footer>${approval()}${brand()}</footer>`;
function density(){let s=L(V('goals')).length+L(V('execution')).length+L(V('recommendations')).length+metrics().length+P().length;['generalGoal','results'].forEach(k=>s+=Math.ceil(V(k).length/160));return s<11?'light':s<22?'medium':'dense'}

// 1 — botanical official frame
function ReportTemplateOne(){return `<article class="v14-sheet tpl14-one ${density()}"><div class="orn top"></div><div class="orn side"></div><header>${identity()}${brand()}</header><section class="title-zone"><small>${E(type())}</small><h1>${E(title())}</h1>${person()}</section>${factbar('facts-one')}<main class="grid-one">${H('generalGoal')?`<section class="block goal"><h2>الهدف العام</h2>${para('generalGoal')}</section>`:''}${H('goals')?`<section class="block goals"><h2>الأهداف</h2><div class="goal-grid">${list('goals')}</div></section>`:''}${metrics().length?`<section class="block metrics"><h2>المؤشرات</h2>${metricRow('metrics-one')}</section>`:''}${H('execution')?`<section class="block execution"><h2>آلية التنفيذ</h2>${list('execution')}</section>`:''}${H('results')?`<section class="block results"><h2>النتائج والأثر</h2>${para('results')}</section>`:''}${H('recommendations')?`<section class="block recs"><h2>التوصيات</h2>${list('recommendations')}</section>`:''}${P().length?`<section class="block evidence"><h2>الشواهد المصورة</h2>${photos('photos-one')}</section>`:''}</main>${footer()}<div class="orn bottom"></div></article>`}

// 2 — activity documentation sheet
function ReportTemplateTwo(){return `<article class="v14-sheet tpl14-two ${density()}"><header>${identity()}${brand()}</header><section class="hero-two"><small>${E(type())}</small><h1>${E(title())}</h1>${person()}</section>${factbar('facts-two')}<main class="two-layout"><section class="two-col">${H('generalGoal')?`<div class="panel"><h2>وصف / هدف التقرير</h2>${para('generalGoal')}</div>`:''}${H('results')?`<div class="panel"><h2>أبرز النتائج</h2>${list('results')}</div>`:''}${H('recommendations')?`<div class="panel note"><h3>ملاحظات وتوصيات</h3>${para('recommendations')}</div>`:''}</section><section class="two-col">${H('goals')?`<div class="panel"><h2>أهداف التقرير</h2><div class="goal-cards">${L(V('goals')).slice(0,4).map((x,i)=>`<div><span>${['◎','◆','◈','◉'][i%4]}</span><b>${E(x)}</b></div>`).join('')}</div></div>`:''}${metrics().length?`<div class="panel"><h2>أثر ومؤشرات التقرير</h2>${metricRow('metrics-two')}</div>`:''}</section>${P().length?`<section class="panel evidence-wide"><h2>الشواهد المصورة</h2>${photos('photos-two')}</section>`:''}</main>${footer()}</article>`}

// 3 — open curved elegant frame
function ReportTemplateThree(){return `<article class="v14-sheet tpl14-three ${density()}"><div class="corner c1"></div><div class="corner c2"></div><header>${identity()}${brand()}</header><section class="three-title"><small>${E(type())}</small><h1>${E(title())}</h1>${person()}</section>${factbar('facts-three')}<main class="three-main">${H('generalGoal')?`<section class="three-focus"><div class="seal">✦</div><h2>الهدف العام</h2>${para('generalGoal')}</section>`:''}${H('goals')?`<section class="three-list"><h2>الأهداف</h2>${list('goals')}</section>`:''}${metrics().length?`<section class="three-stats"><h2>المؤشرات</h2>${metricRow('metrics-three')}</section>`:''}${H('execution')?`<section class="three-flow"><h2>التنفيذ</h2>${L(V('execution')).map((x,i)=>`<div><i>${i+1}</i><span>${E(x)}</span></div>`).join('')}</section>`:''}${H('results')?`<section class="three-impact"><h2>الأثر والنتائج</h2>${para('results')}</section>`:''}${P().length?`<section class="three-evidence"><h2>الشواهد</h2>${photos('photos-three')}</section>`:''}</main>${footer()}</article>`}

// 4 — centered title with connected journey
function ReportTemplateFour(){const stages=[];if(H('generalGoal'))stages.push(['الهدف',V('generalGoal')]);if(H('goals'))stages.push(['الأهداف',L(V('goals')).join(' • ')]);if(H('execution'))L(V('execution')).slice(0,3).forEach((x,i)=>stages.push([i?'مرحلة التنفيذ':'التنفيذ',x]));if(H('results'))stages.push(['النتائج',V('results')]);return `<article class="v14-sheet tpl14-four ${density()}"><header>${identity()}${brand()}</header><section class="four-title"><div class="health-mark">✚</div><small>${E(type())}</small><h1>${E(title())}</h1>${person()}</section>${factbar('facts-four')}<main><section class="journey">${stages.slice(0,6).map((s,i)=>`<div class="stage"><div class="stage-no">${String(i+1).padStart(2,'0')}</div><div><h2>${E(s[0])}</h2><p>${E(s[1])}</p></div></div>`).join('')}</section>${metrics().length?`<section class="four-metrics"><h2>مؤشرات الأثر</h2>${metricRow('metrics-four')}</section>`:''}${P().length?`<section class="four-photos"><h2>الشواهد المصورة</h2>${photos('photos-four')}</section>`:''}${H('recommendations')?`<section class="four-recs"><h2>التوصيات</h2>${list('recommendations')}</section>`:''}</main>${footer()}</article>`}

// 5 — modular geometric report
function ReportTemplateFive(){return `<article class="v14-sheet tpl14-five ${density()}"><header>${identity()}${brand()}</header><section class="five-title"><small>${E(type())}</small><h1>${E(title())}</h1>${person()}</section>${factbar('facts-five')}<main class="five-grid">${H('generalGoal')?`<section class="five-goal"><h2>الهدف العام</h2>${para('generalGoal')}</section>`:''}${H('goals')?`<section class="five-goals"><h2>الأهداف</h2>${list('goals')}</section>`:''}${metrics().length?`<section class="five-metrics"><h2>الإحصائيات والمؤشرات</h2>${metricRow('metrics-five')}</section>`:''}${H('execution')?`<section class="five-process"><h2>آلية التنفيذ</h2>${L(V('execution')).map((x,i)=>`<span><i>${i+1}</i>${E(x)}</span>`).join('')}</section>`:''}${H('results')?`<section class="five-results"><h2>النتائج</h2>${para('results')}</section>`:''}${H('recommendations')?`<section class="five-recs"><h2>التوصيات</h2>${list('recommendations')}</section>`:''}${P().length?`<section class="five-evidence"><h2>الشواهد المصورة</h2>${photos('photos-five')}</section>`:''}</main>${footer()}</article>`}

const REG={aurora:ReportTemplateOne,editorial:ReportTemplateTwo,minimal:ReportTemplateThree,prism:ReportTemplateFour,impact:ReportTemplateFive};
function fit(){const s=q('.v14-sheet');if(!s)return;s.style.setProperty('--fit','1');requestAnimationFrame(()=>{const h=s.scrollHeight;if(h>1123){const z=Math.max(.76,1123/h);s.style.setProperty('--fit',z.toFixed(3));s.classList.toggle('auto-dense',z<.9)}})}
window.render=function(){const prev=q('#reportPreview');if(!prev)return;const key=F.elements.theme?.value||'aurora';prev.className=`report v14-report theme-${key}`;prev.style.transform=`scale(${typeof zoom!=='undefined'?zoom:.72})`;prev.innerHTML=(REG[key]||ReportTemplateOne)();const z=q('#zoomText');if(z)z.textContent=Math.round((typeof zoom!=='undefined'?zoom:.72)*100)+'%';fit()};
const names={aurora:['الإطار التعليمي النباتي','إطار رسمي تركوازي وذهبي'],editorial:['توثيق النشاط التعليمي','تقرير منظم بالأهداف والنتائج والشواهد'],minimal:['الهوية الهادئة','إطار مفتوح بخطوط رفيعة ومساحات مريحة'],prism:['مسار التوثيق الرسمي','عنوان مركزي ومسار مراحل ومؤشرات'],impact:['النموذج الهندسي الحديث','تقسيمات هندسية للمحتوى والبيانات']};
Object.entries(names).forEach(([k,[a,b]])=>{const c=q(`input[name="theme"][value="${k}"]`)?.closest('.theme-card');if(c){const t=c.querySelector('strong'),s=c.querySelector('span');if(t)t.textContent=a;if(s)s.textContent=b;}});
const badge=q('.side-intro .eyebrow');if(badge)badge.textContent='V14';document.title='توثيق — القوالب التعليمية V14';
F.addEventListener('input',()=>requestAnimationFrame(window.render));F.addEventListener('change',()=>requestAnimationFrame(window.render));
document.addEventListener('click',e=>{const c=e.target.closest('.theme-card');if(c){const r=c.querySelector('input[type=radio]');if(r&&!r.checked){r.checked=true;r.dispatchEvent(new Event('change',{bubbles:true}))}}});
setTimeout(()=>window.render(),60);
})();