// V4.2 — premium single-page infographic report engine
(function(){
 if(!document.querySelector('link[href="./v42.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./v42.css';document.head.appendChild(l)}
 const badge=document.querySelector('.side-intro .eyebrow');if(badge)badge.textContent='V4.2';document.title='توثيق — صانع التقارير الذكي V4.2';
 const E=n=>form.elements[n], has=n=>!!(E(n)&&String(E(n).value||'').trim()), V=n=>has(n)?String(E(n).value).trim():'', safe=s=>esc(String(s||'')), L=s=>lines(s||'');
 const statsData=()=>{let a=[];[['students','الطلاب',''],['femaleStudents','الطالبات',''],['teachers','المعلمون',''],['femaleTeachers','المعلمات',''],['beneficiaries','المستفيدون',''],['attendance','الحضور','%'],['satisfaction','الرضا','%'],['activities','الأنشطة',''],['target','المستهدف',''],['achieved','المتحقق','']].forEach(([n,l,u])=>{if(has(n)&&num(n)>0)a.push({l,v:num(n),u})});$$('.metric-name').forEach((m,i)=>{let x=Number($$('.metric-value')[i]?.value)||0;if(m.value.trim()&&x>0)a.push({l:m.value.trim(),v:x,u:''})});return a};
 function bullets(text){return L(text).map((x,i)=>`<div class="p-bullet"><i>${String(i+1).padStart(2,'0')}</i><span>${safe(x)}</span></div>`).join('')}
 function identity(){return `<div class="p-identity"><img src="./moe-logo.svg?v=42" alt="وزارة التعليم"><div>${has('authority')?`<b>${safe(V('authority'))}</b>`:''}${has('school')?`<strong>${safe(V('school'))}</strong>`:''}</div></div>`}
 function person(){if(!has('executor')&&!has('jobTitle'))return'';return `<div class="p-person">${has('jobTitle')?`<span>${safe(V('jobTitle'))}</span>`:''}${has('executor')?`<b>${safe(V('executor'))}</b>`:''}</div>`}
 function facts(){let a=[];[['date','تاريخ التنفيذ'],['duration','المدة'],['audience','الفئة المستهدفة'],['location','مكان التنفيذ'],['department','القسم / الوحدة']].forEach(([n,l])=>{if(has(n))a.push([l,V(n)])});return a.length?`<div class="p-facts">${a.map(x=>`<div><small>${x[0]}</small><b>${safe(x[1])}</b></div>`).join('')}</div>`:''}
 function stats(){let s=statsData();if(!s.length)return'';return `<section class="p-section p-stats"><h2>مؤشرات البرنامج</h2><div class="p-statgrid">${s.slice(0,6).map((x,i)=>`<div class="p-stat s${i}"><strong>${x.v}${x.u}</strong><span>${safe(x.l)}</span><i style="--pct:${x.u==='%'?Math.min(100,x.v):Math.min(100,20+x.v)}"></i></div>`).join('')}</div></section>`}
 function gallery(){if(!images.length)return'';return `<section class="p-section p-evidence"><h2>الشواهد المصورة</h2><div class="p-gallery n${images.length}">${images.map((x,i)=>`<figure><img src="${x.src}">${x.caption?`<figcaption>${safe(x.caption)}</figcaption>`:''}</figure>`).join('')}</div></section>`}
 function textSections(){let out='';if(has('generalGoal'))out+=`<section class="p-section p-goal"><h2>الهدف العام</h2><p>${safe(V('generalGoal')).replace(/\n/g,'<br>')}</p></section>`;if(has('goals'))out+=`<section class="p-section p-goals"><h2>أهداف البرنامج</h2><div class="p-bullets">${bullets(V('goals'))}</div></section>`;if(has('execution'))out+=`<section class="p-section p-exec"><h2>آلية التنفيذ</h2><p>${safe(V('execution')).replace(/\n/g,'<br>')}</p></section>`;out+=stats();if(has('results'))out+=`<section class="p-section p-results"><h2>النتائج والأثر</h2><p>${safe(V('results')).replace(/\n/g,'<br>')}</p></section>`;if(has('recommendations'))out+=`<section class="p-section p-recs"><h2>التوصيات</h2><div class="p-bullets">${bullets(V('recommendations'))}</div></section>`;out+=gallery();return out}
 function fit(){let sh=$('.premium-sheet'), inn=$('.premium-inner');if(!sh||!inn)return;inn.style.transform='none';inn.style.width='100%';requestAnimationFrame(()=>{let h=inn.scrollHeight,scale=Math.min(1,1100/h);inn.style.transform=`scale(${scale})`;inn.style.transformOrigin='top right';inn.style.width=`${100/scale}%`;sh.dataset.fit=scale.toFixed(3)})}
 render=function(){let theme=E('theme')?.value||'aurora',title=has('title')?V('title'):'عنوان التقرير';$('#reportPreview').className=`report premium theme-${theme}`;$('#reportPreview').style.transform=`scale(${zoom})`;$('#reportPreview').innerHTML=`<article class="premium-sheet"><div class="premium-inner"><header class="premium-hero">${identity()}<div class="p-title"><h1>${safe(title)}</h1>${person()}</div></header><main class="premium-body">${facts()}<div class="premium-content">${textSections()}</div>${has('approver')?`<div class="p-sign"><span>الاعتماد</span><b>${safe(V('approver'))}</b></div>`:''}</main><footer class="premium-footer"><span>${has('school')?safe(V('school')):''}</span><i></i></footer></div></article>`;$('#zoomText').textContent=Math.round(zoom*100)+'%';fit()};
 form.addEventListener('input',render);form.addEventListener('change',render);render();
})();