// V7 — clean five-template infographic renderer. Depends only on app.js globals.
(function(){
 const F=document.querySelector('#reportForm'); if(!F)return;
 const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
 const v=n=>String(F.elements[n]?.value||'').trim(), has=n=>!!v(n), nv=n=>Number(v(n))||0;
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const lines=s=>String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
 const IMG=()=>Array.isArray(images)?images:[];
 const title=()=>v('title')||'عنوان التقرير';
 const school=()=>v('school');
 const logo=()=>'<img class="v7-logo" src="./moe-logo.svg?v=70" alt="وزارة التعليم">';
 function id(){return `<div class="v7-id">${logo()}<div>${has('authority')?`<small>${esc(v('authority'))}</small>`:''}${school()?`<strong>${esc(school())}</strong>`:''}</div></div>`}
 function brand(){return `<div class="v7-brand"><i>ت</i><div>توثيق<small>هوية تعليمية للتقارير</small></div></div>`}
 function person(){return (has('jobTitle')||has('executor'))?`<div class="v7-person">${has('jobTitle')?`<span>${esc(v('jobTitle'))}</span>`:''}${has('executor')?`<b>${esc(v('executor'))}</b>`:''}</div>`:''}
 function facts(){return [['date','التاريخ'],['duration','المدة'],['audience','الفئة المستهدفة'],['location','المكان'],['department','القسم / الوحدة']].filter(([k])=>has(k)).map(([k,l])=>({l,val:v(k)}))}
 function factsHTML(){let f=facts();return f.length?`<div class="v7-facts">${f.map(x=>`<div class="v7-fact"><small>${x.l}</small><b>${esc(x.val)}</b></div>`).join('')}</div>`:''}
 function metrics(){let a=[];[['beneficiaries','المستفيدون',''],['attendance','الحضور','%'],['satisfaction','الرضا','%'],['activities','الأنشطة',''],['students','الطلاب',''],['femaleStudents','الطالبات',''],['teachers','المعلمون',''],['femaleTeachers','المعلمات','']].forEach(([k,l,u])=>{if(has(k)&&nv(k)>0)a.push({l,val:nv(k),u})});qa('.metric-name').forEach((e,i)=>{let val=Number(qa('.metric-value')[i]?.value)||0;if(e.value.trim()&&val>0)a.push({l:e.value.trim(),val,u:''})});if(nv('target')>0&&has('achieved'))a.unshift({l:'نسبة التحقق',val:Math.min(100,Math.round(nv('achieved')/nv('target')*100)),u:'%'});else{if(nv('target')>0)a.push({l:'المستهدف',val:nv('target'),u:''});if(nv('achieved')>0)a.push({l:'المتحقق',val:nv('achieved'),u:''})}return a.slice(0,6)}
 function metricsHTML(){let a=metrics();return a.length?`<div class="v7-metrics">${a.map(x=>`<div class="v7-metric" tabindex="0"><strong>${x.val}${x.u}</strong><small>${esc(x.l)}</small></div>`).join('')}</div>`:''}
 function listHTML(text){return `<div class="v7-list">${lines(text).map((x,i)=>`<div class="v7-item"><i>${String(i+1).padStart(2,'0')}</i><span>${esc(x)}</span></div>`).join('')}</div>`}
 function sec(cls,h,body){return body?`<section class="v7-section ${cls}"><h2>${h}</h2>${body}</section>`:''}
 function p(n){return has(n)?`<p>${esc(v(n)).replace(/\n/g,'<br>')}</p>`:''}
 function gallery(){let a=IMG();return a.length?`<div class="v7-gallery n${a.length}">${a.map((x,i)=>`<figure><img src="${x.src}" alt="شاهد ${i+1}">${x.caption?`<figcaption>${esc(x.caption)}</figcaption>`:''}</figure>`).join('')}</div>`:''}
 function approval(){return has('approver')?`<span>الاعتماد: <b>${esc(v('approver'))}</b></span>`:''}

 function t1(){return `<article class="v7-sheet t1"><header>${id()}${brand()}</header><div class="t1-hero"><div><small>${esc(v('reportType')||'تقرير تعليمي')}</small><h1>${esc(title())}</h1>${person()}</div>${metricsHTML()}</div>${factsHTML()}<main class="t1-flow">${sec('goal','الهدف العام',p('generalGoal'))}${has('goals')?sec('goals','الأهداف',listHTML(v('goals'))):''}${sec('exec','آلية التنفيذ',p('execution'))}${sec('results','النتائج والأثر',p('results'))}${has('recommendations')?sec('recs','التوصيات',listHTML(v('recommendations'))):''}${IMG().length?sec('evidence','الشواهد المصورة',gallery()):''}</main><footer>${approval()}<span>${esc(school())}</span></footer></article>`}
 function t2(){return `<article class="v7-sheet t2"><header>${brand()}${id()}</header><div class="t2-hero"><div><small>قياس الأثر التعليمي</small><h1>${esc(title())}</h1>${person()}</div><div class="t2-orbit">${metricsHTML()}</div></div>${factsHTML()}<main class="t2-body"><div>${has('goals')?sec('goals','المستهدفات',listHTML(v('goals'))):''}${sec('exec','التنفيذ',p('execution'))}</div><div class="middle">${sec('goal','الهدف المحوري',p('generalGoal'))}${sec('results','الأثر المتحقق',p('results'))}${has('recommendations')?sec('recs','الخطوة التالية',listHTML(v('recommendations'))):''}</div><div>${IMG().length?sec('evidence','شواهد الأثر',gallery()):''}</div>${IMG().length>3?sec('evidence','المشهد المصور',gallery()):''}</main><footer>${approval()}<span>${esc(school())}</span></footer></article>`}
 function t3(){return `<article class="v7-sheet t3"><div class="t3-topline"></div><header>${id()}${brand()}</header><div class="t3-title"><div><small>${esc(v('reportType')||'تقرير تعليمي')}</small><h1>${esc(title())}</h1></div>${person()}</div>${factsHTML()}<main class="t3-editorial"><div class="t3-story">${sec('goal','الفكرة والهدف',p('generalGoal'))}${sec('exec','قصة التنفيذ',p('execution'))}${sec('results','ما الذي تحقق؟',p('results'))}${has('recommendations')?sec('recs','التوصيات',listHTML(v('recommendations'))):''}</div><aside class="t3-side">${metricsHTML()}${has('goals')?sec('goals','أهداف مختصرة',listHTML(v('goals'))):''}</aside>${IMG().length?sec('evidence','الشواهد المصورة',gallery()):''}</main><footer>${approval()}<span>${esc(school())}</span></footer></article>`}
 function node(n,body){return body?`<div class="t4-node"><i>${String(n).padStart(2,'0')}</i>${body}</div>`:''}
 function t4(){let m=metrics();return `<article class="v7-sheet t4"><header>${id()}${brand()}</header><div class="t4-hero"><div class="t4-number">${m[0]?`${m[0].val}${m[0].u}`:'01'}</div><div><small>رحلة إنجاز تعليمية</small><h1>${esc(title())}</h1>${person()}</div></div>${factsHTML()}<main class="t4-path">${node(1,sec('goal','الهدف',p('generalGoal')))}${node(2,has('goals')?sec('goals','الأهداف',listHTML(v('goals'))):'')}${node(3,sec('exec','التنفيذ',p('execution')))}${node(4,metricsHTML())}${node(5,sec('results','الأثر',p('results')))}${node(6,IMG().length?gallery():'')}</main>${has('recommendations')?`<div style="margin:0 30px">${sec('recs','التوصيات',listHTML(v('recommendations')))}</div>`:''}<footer>${approval()}<span>${esc(school())}</span></footer></article>`}
 function t5(){return `<article class="v7-sheet t5"><div class="t5-wave"></div><header>${brand()}${id()}</header><div class="t5-hero"><div><small>مشهد تعليمي موثّق</small><h1>${esc(title())}</h1>${person()}</div>${factsHTML()}</div><main class="t5-layout"><div class="t5-card">${sec('goal','الهدف العام',p('generalGoal'))}${IMG().length?gallery():''}</div><div class="t5-card">${has('goals')?sec('goals','الأهداف',listHTML(v('goals'))):''}${metricsHTML()}${sec('exec','التنفيذ',p('execution'))}${sec('results','النتائج والأثر',p('results'))}</div>${has('recommendations')?`<div class="t5-card wide">${sec('recs','التوصيات',listHTML(v('recommendations')))}</div>`:''}</main><footer>${approval()}<span>${esc(school())}</span>${brand()}</footer></article>`}
 const REG={aurora:t1,editorial:t2,minimal:t3,prism:t4,impact:t5};
 function fit(){let s=q('.v7-sheet');if(!s)return;requestAnimationFrame(()=>{if(s.scrollHeight>1123)s.style.zoom=Math.max(.76,1123/s.scrollHeight);else s.style.zoom=1})}
 window.render=function(){let theme=F.elements.theme?.value||'aurora',prev=q('#reportPreview');if(!prev)return;prev.className=`report v7-report theme-${theme}`;prev.style.transform=`scale(${zoom})`;prev.innerHTML=(REG[theme]||t1)();let z=q('#zoomText');if(z)z.textContent=Math.round(zoom*100)+'%';fit()};
 const names={aurora:['مسار التعليم','تقرير إنفوجرافيك متصل من الهدف إلى الأثر'],editorial:['نبض الأثر','قراءة بصرية للمؤشرات والنتائج'],minimal:['المجلة التعليمية','تقرير تحريري بصري منظم'],prism:['رحلة الإنجاز','مسار إنفوجرافيك مرقّم للتنفيذ والأثر'],impact:['المشهد التعليمي','تكوين بصري يدمج المحتوى والصور والبيانات']};
 Object.entries(names).forEach(([x,[a,b]])=>{let c=q(`input[name="theme"][value="${x}"]`)?.closest('.theme-card');if(c){c.querySelector('strong').textContent=a;c.querySelector('span').textContent=b}});
 q('.side-intro .eyebrow').textContent='V7'; document.title='توثيق — صانع التقارير الذكي V7';
 F.addEventListener('input',()=>requestAnimationFrame(window.render));F.addEventListener('change',()=>requestAnimationFrame(window.render));
 document.addEventListener('click',e=>{let m=e.target.closest('.v7-metric');if(m){qa('.v7-metric').forEach(x=>x!==m&&x.classList.remove('active'));m.classList.toggle('active')}});
 setTimeout(window.render,60);
})();