// V8 — clean infographic engine: five independent educational report renderers
(function(){
'use strict';
const form=document.querySelector('#reportForm'); if(!form)return;
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const V=n=>String(form.elements[n]?.value||'').trim(), H=n=>!!V(n), N=n=>Number(V(n))||0;
const E=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LS=s=>String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
const imgs=()=>typeof images!=='undefined'&&Array.isArray(images)?images:[];
const reportTitle=()=>V('title')||'عنوان التقرير';
const reportType=()=>V('reportType')||'تقرير تعليمي';
const logo=()=>'<img class="r8-logo" src="./moe-logo-official.png?v=80" alt="وزارة التعليم" onerror="this.src=\'./moe-logo.svg?v=80\'">';
const identity=()=>`<div class="r8-identity">${logo()}<div>${H('authority')?`<small>${E(V('authority'))}</small>`:''}${H('school')?`<strong>${E(V('school'))}</strong>`:''}</div></div>`;
const signature=()=>'<span class="r8-signature"><b>توثيق</b><i></i></span>';
const executor=()=>H('executor')||H('jobTitle')?`<div class="r8-executor">${H('jobTitle')?`<small>${E(V('jobTitle'))}</small>`:''}${H('executor')?`<b>${E(V('executor'))}</b>`:''}</div>`:'';
const facts=()=>[['date','التاريخ'],['duration','المدة'],['audience','الفئة المستهدفة'],['location','المكان'],['department','القسم / الوحدة']].filter(([k])=>H(k)).map(([k,l])=>({label:l,value:V(k)}));
function metricData(){const a=[];[['beneficiaries','المستفيدون',''],['attendance','الحضور','%'],['satisfaction','الرضا','%'],['activities','الأنشطة',''],['students','الطلاب',''],['femaleStudents','الطالبات',''],['teachers','المعلمون',''],['femaleTeachers','المعلمات','']].forEach(([k,l,u])=>{if(H(k)&&N(k)>0)a.push({label:l,value:N(k),unit:u,type:u==='%'?'percent':'count'})});qa('.metric-name').forEach((el,i)=>{const x=Number(qa('.metric-value')[i]?.value)||0;if(el.value.trim()&&x>0)a.push({label:el.value.trim(),value:x,unit:'',type:'count'})});if(N('target')>0&&H('achieved'))a.unshift({label:'تحقق المستهدف',value:Math.min(100,Math.round(N('achieved')/N('target')*100)),unit:'%',type:'percent'});else{if(N('target')>0)a.push({label:'المستهدف',value:N('target'),unit:'',type:'count'});if(N('achieved')>0)a.push({label:'المتحقق',value:N('achieved'),unit:'',type:'count'})}return a.slice(0,8)}
const paragraph=n=>H(n)?`<p>${E(V(n)).replace(/\n/g,'<br>')}</p>`:'';
const items=n=>H(n)?LS(V(n)).map((x,i)=>`<div class="r8-point"><i>${String(i+1).padStart(2,'0')}</i><span>${E(x)}</span></div>`).join(''):'';
function factRail(cls=''){const a=facts();return a.length?`<div class="r8-facts ${cls}">${a.map((x,i)=>`<div><i>${String(i+1).padStart(2,'0')}</i><span><small>${x.label}</small><b>${E(x.value)}</b></span></div>`).join('')}</div>`:''}
function kpis(cls=''){const a=metricData();return a.length?`<div class="r8-kpis ${cls}">${a.map((x,i)=>x.type==='percent'?`<div class="r8-kpi percent k${i}"><div class="r8-ring" style="--p:${Math.min(100,x.value)}"><strong>${x.value}%</strong></div><span>${E(x.label)}</span></div>`:`<div class="r8-kpi count k${i}"><strong>${x.value}</strong><span>${E(x.label)}</span></div>`).join('')}</div>`:''}
function photoSet(cls=''){const a=imgs();if(!a.length)return'';const shown=a.slice(0,10);return `<div class="r8-photos ${cls} n${shown.length}">${shown.map((x,i)=>`<figure><img src="${x.src}" alt="شاهد ${i+1}">${x.caption?`<figcaption>${E(x.caption)}</figcaption>`:''}</figure>`).join('')}</div>`}
const footer=()=>`<footer>${H('approver')?`<span class="r8-approve">اعتماد <b>${E(V('approver'))}</b></span>`:'<span></span>'}${signature()}</footer>`;
function density(){let score=LS(V('goals')).length+LS(V('recommendations')).length+metricData().length+imgs().length;['generalGoal','execution','results'].forEach(x=>score+=Math.ceil(V(x).length/180));return score<11?'light':score<22?'medium':'dense'}

// 1 — Ribbon / institutional infographic
function ReportTemplateOne(){return `<article class="r8-sheet tpl-ribbon ${density()}"><div class="rb-corner"></div><header>${identity()}${signature()}</header><section class="rb-hero"><div><small>${E(reportType())}</small><h1>${E(reportTitle())}</h1>${executor()}</div>${kpis('rb-kpis')}</section>${factRail('rb-facts')}<main class="rb-main"><div class="rb-column primary">${H('generalGoal')?`<section class="rb-goal"><span>الهدف</span>${paragraph('generalGoal')}</section>`:''}${H('goals')?`<section class="rb-objectives"><h2>الأهداف</h2>${items('goals')}</section>`:''}</div><div class="rb-column flow">${H('execution')?`<section class="rb-process"><h2>مسار التنفيذ</h2>${LS(V('execution')).map((x,i)=>`<div class="rb-step"><i>${i+1}</i><p>${E(x)}</p></div>`).join('')}</section>`:''}${H('results')?`<section class="rb-impact"><h2>الأثر والنتائج</h2>${paragraph('results')}</section>`:''}</div>${imgs().length?`<section class="rb-evidence">${photoSet('rb-photos')}</section>`:''}${H('recommendations')?`<section class="rb-recs"><h2>التوصيات</h2><div>${items('recommendations')}</div></section>`:''}</main>${footer()}</article>`}

// 2 — Impact radar / circular data story
function ReportTemplateTwo(){const m=metricData();return `<article class="r8-sheet tpl-orbit ${density()}"><div class="or-bg"></div><header>${identity()}${executor()}</header><section class="or-title"><small>قراءة بصرية للأثر</small><h1>${E(reportTitle())}</h1><span>${E(reportType())}</span></section><section class="or-radar"><div class="or-center"><b>${m[0]?`${m[0].value}${m[0].unit}`:'توثيق'}</b><small>${m[0]?E(m[0].label):'أثر تعليمي'}</small></div>${m.slice(1,7).map((x,i)=>`<div class="or-node n${i+1}"><strong>${x.value}${x.unit}</strong><small>${E(x.label)}</small></div>`).join('')}</section>${factRail('or-facts')}<main class="or-main"><section class="or-left">${H('generalGoal')?`<div class="or-callout"><h2>الهدف المحوري</h2>${paragraph('generalGoal')}</div>`:''}${H('results')?`<div class="or-result"><h2>ما الذي تغيّر؟</h2>${paragraph('results')}</div>`:''}</section><section class="or-mid">${H('goals')?`<h2>مستهدفات البرنامج</h2>${items('goals')}`:''}${H('execution')?`<div class="or-timeline"><h2>التنفيذ</h2>${LS(V('execution')).map((x,i)=>`<div><i></i><span>${E(x)}</span></div>`).join('')}</div>`:''}</section><section class="or-right">${imgs().length?photoSet('or-photos'):''}${H('recommendations')?`<div class="or-next"><h2>الخطوة التالية</h2>${items('recommendations')}</div>`:''}</section></main>${footer()}</article>`}

// 3 — Educational editorial poster / magazine infographic
function ReportTemplateThree(){return `<article class="r8-sheet tpl-editorial ${density()}"><div class="ed-bar"></div><header>${signature()}${identity()}</header><section class="ed-mast"><div class="ed-index">تقرير<br>تعليمي</div><div><small>${E(reportType())}</small><h1>${E(reportTitle())}</h1>${executor()}</div></section>${factRail('ed-facts')}<main class="ed-layout"><section class="ed-story">${H('generalGoal')?`<div class="ed-lead"><b>الفكرة</b>${paragraph('generalGoal')}</div>`:''}${H('execution')?`<div class="ed-copy"><h2>قصة التنفيذ</h2>${paragraph('execution')}</div>`:''}${H('results')?`<div class="ed-quote"><span>الأثر</span>${paragraph('results')}</div>`:''}</section><aside class="ed-data">${kpis('ed-kpis')}${H('goals')?`<section><h2>أهداف مختصرة</h2>${items('goals')}</section>`:''}</aside>${imgs().length?`<section class="ed-gallery">${photoSet('ed-photos')}</section>`:''}${H('recommendations')?`<section class="ed-recs"><h2>توصيات قابلة للتنفيذ</h2>${items('recommendations')}</section>`:''}</main>${footer()}</article>`}

// 4 — Journey / numbered learning path
function ReportTemplateFour(){const stages=[];if(H('generalGoal'))stages.push(['الانطلاق','generalGoal','p']);if(H('goals'))stages.push(['المستهدفات','goals','list']);if(H('execution'))stages.push(['التنفيذ','execution','p']);if(metricData().length)stages.push(['القياس','metrics','metrics']);if(H('results'))stages.push(['الأثر','results','p']);if(imgs().length)stages.push(['الشواهد','photos','photos']);return `<article class="r8-sheet tpl-journey ${density()}"><header>${identity()}${signature()}</header><section class="jr-hero"><div class="jr-badge">رحلة<br>الإنجاز</div><div><small>${E(reportType())}</small><h1>${E(reportTitle())}</h1>${executor()}</div></section>${factRail('jr-facts')}<main class="jr-path">${stages.map((s,i)=>`<section class="jr-stage s${i}"><div class="jr-num">${String(i+1).padStart(2,'0')}</div><div class="jr-content"><h2>${s[0]}</h2>${s[2]==='p'?paragraph(s[1]):s[2]==='list'?items(s[1]):s[2]==='metrics'?kpis('jr-kpis'):photoSet('jr-photos')}</div></section>`).join('')}</main>${H('recommendations')?`<section class="jr-end"><span>خطوة قادمة</span>${items('recommendations')}</section>`:''}${footer()}</article>`}

// 5 — Mosaic / integrated evidence + data composition
function ReportTemplateFive(){return `<article class="r8-sheet tpl-mosaic ${density()}"><div class="mo-shape a"></div><div class="mo-shape b"></div><header>${identity()}${signature()}</header><section class="mo-hero"><div><span>مشهد تعليمي موثّق</span><h1>${E(reportTitle())}</h1>${executor()}</div>${factRail('mo-facts')}</section><main class="mo-grid"><section class="mo-a">${H('generalGoal')?`<div class="mo-goal"><small>الهدف العام</small>${paragraph('generalGoal')}</div>`:''}${imgs().length?photoSet('mo-photos'):''}</section><section class="mo-b">${kpis('mo-kpis')}${H('goals')?`<div class="mo-objectives"><h2>الأهداف</h2>${items('goals')}</div>`:''}</section><section class="mo-c">${H('execution')?`<div class="mo-process"><h2>التنفيذ</h2>${LS(V('execution')).map((x,i)=>`<span><i>${i+1}</i>${E(x)}</span>`).join('')}</div>`:''}${H('results')?`<div class="mo-impact"><h2>النتائج والأثر</h2>${paragraph('results')}</div>`:''}</section>${H('recommendations')?`<section class="mo-d"><h2>التوصيات</h2>${items('recommendations')}</section>`:''}</main>${footer()}</article>`}

const ReportTemplateRegistry={aurora:ReportTemplateOne,editorial:ReportTemplateTwo,minimal:ReportTemplateThree,prism:ReportTemplateFour,impact:ReportTemplateFive};
function fit(){const sheet=q('.r8-sheet');if(!sheet)return;sheet.style.setProperty('--scale','1');requestAnimationFrame(()=>{const h=sheet.scrollHeight;if(h>1123){const s=Math.max(.78,Math.min(1,1123/h));sheet.style.setProperty('--scale',s.toFixed(3));sheet.classList.toggle('auto-dense',s<.91)}})}
window.render=function(){const preview=q('#reportPreview');if(!preview)return;const key=form.elements.theme?.value||'aurora';preview.className=`report r8-report theme-${key}`;preview.style.transform=`scale(${typeof zoom!=='undefined'?zoom:.72})`;preview.innerHTML=(ReportTemplateRegistry[key]||ReportTemplateOne)();const z=q('#zoomText');if(z)z.textContent=Math.round((typeof zoom!=='undefined'?zoom:.72)*100)+'%';fit()};
const labels={aurora:['مسار المعرفة','إنفوجرافيك مؤسسي متصل من الهدف إلى الأثر'],editorial:['مدار الأثر','تكوين دائري يحوّل المؤشرات إلى قصة بصرية'],minimal:['صفحة التعليم','أسلوب تحريري بصري حديث للتوثيق الرسمي'],prism:['رحلة الإنجاز','مسار مرقّم يشرح التنفيذ والقياس والنتيجة'],impact:['فسيفساء التعلّم','مزيج متكامل بين الصور والبيانات والمحتوى']};
Object.entries(labels).forEach(([key,[name,desc]])=>{const card=q(`input[name="theme"][value="${key}"]`)?.closest('.theme-card');if(card){card.querySelector('strong').textContent=name;card.querySelector('span').textContent=desc;card.dataset.template=key}});
const badge=q('.side-intro .eyebrow');if(badge)badge.textContent='V8';document.title='توثيق — صانع التقارير الذكي V8';
form.addEventListener('input',()=>requestAnimationFrame(window.render));form.addEventListener('change',()=>requestAnimationFrame(window.render));
document.addEventListener('click',e=>{const card=e.target.closest('.theme-card');if(card){qa('.theme-card').forEach(x=>x.classList.toggle('selected',x===card));const radio=card.querySelector('input[type=radio]');if(radio&&!radio.checked){radio.checked=true;radio.dispatchEvent(new Event('change',{bubbles:true}))}}const k=e.target.closest('.r8-kpi,.or-node,.jr-stage');if(k)k.classList.toggle('active')});
setTimeout(window.render,80);
})();