// V9 — reference-inspired educational infographic templates
(function(){
'use strict';
const F=document.querySelector('#reportForm'); if(!F)return;
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const V=n=>String(F.elements[n]?.value||'').trim(), H=n=>!!V(n), N=n=>Number(V(n))||0;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=s=>String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
const photos=()=>typeof images!=='undefined'&&Array.isArray(images)?images:[];
const title=()=>V('title')||'عنوان التقرير الرئيسي';
const logo=()=>'<img class="v9-logo" src="./moe-logo-official.png?v=90" onerror="this.src=\'./moe-logo.svg?v=90\'" alt="وزارة التعليم">';
const ident=()=>`<div class="v9-ident">${logo()}<div>${H('authority')?`<small>${esc(V('authority'))}</small>`:''}${H('school')?`<b>${esc(V('school'))}</b>`:''}</div></div>`;
const stamp=()=>'<div class="v9-stamp"><b>توثيق</b><span>تعليم</span></div>';
const person=()=>H('executor')||H('jobTitle')?`<div class="v9-person">${H('jobTitle')?`<small>${esc(V('jobTitle'))}</small>`:''}${H('executor')?`<b>${esc(V('executor'))}</b>`:''}</div>`:'';
const facts=()=>[['beneficiaries','المستفيدون'],['attendance','نسبة الحضور'],['audience','الفئة المستهدفة'],['location','مكان التنفيذ'],['duration','مدة التنفيذ'],['date','تاريخ التنفيذ']].filter(([k])=>H(k)).map(([k,l])=>({k,l,v:V(k)}));
function metricData(){const a=[];[['beneficiaries','المستفيدون',''],['attendance','نسبة الحضور','%'],['satisfaction','نسبة الرضا','%'],['activities','الأنشطة',''],['students','الطلاب',''],['femaleStudents','الطالبات',''],['teachers','المعلمون',''],['femaleTeachers','المعلمات','']].forEach(([k,l,u])=>{if(H(k)&&N(k)>0)a.push({l,v:N(k),u})});if(N('target')>0)a.push({l:'المستهدف',v:N('target'),u:''});if(N('achieved')>0)a.push({l:'المتحقق',v:N('achieved'),u:''});qa('.metric-name').forEach((e,i)=>{const x=Number(qa('.metric-value')[i]?.value)||0;if(e.value.trim()&&x>0)a.push({l:e.value.trim(),v:x,u:''})});return a.slice(0,8)}
const p=n=>H(n)?`<p>${esc(V(n)).replace(/\n/g,'<br>')}</p>`:'';
const bullet=(text,cls='')=>lines(text).map((x,i)=>`<div class="v9-bullet ${cls}"><i>${String(i+1).padStart(2,'0')}</i><span>${esc(x)}</span></div>`).join('');
const factStrip=(cls='')=>{const a=facts();return a.length?`<div class="v9-facts ${cls}">${a.map(x=>`<div><small>${x.l}</small><b>${esc(x.v)}${x.k==='attendance'?'%':''}</b></div>`).join('')}</div>`:''};
function rings(cls=''){const a=metricData().slice(0,5);return a.length?`<div class="v9-rings ${cls}">${a.map((x,i)=>{const pct=x.u==='%'?Math.min(100,x.v):Math.min(100,25+x.v);return `<div class="v9-ring"><i style="--p:${pct}"><b>${x.v}${x.u}</b></i><span>${esc(x.l)}</span></div>`}).join('')}</div>`:''}
function kpiRow(cls=''){const a=metricData().slice(0,6);return a.length?`<div class="v9-kpis ${cls}">${a.map((x,i)=>`<div><span class="ico">${['◉','✦','▣','◎','◆','●'][i%6]}</span><b>${x.v}${x.u}</b><small>${esc(x.l)}</small></div>`).join('')}</div>`:''}
function gallery(cls=''){const a=photos().slice(0,10);if(!a.length)return'';return `<div class="v9-gallery ${cls} n${a.length}">${a.map((im,i)=>`<figure><img src="${im.src}" alt="شاهد ${i+1}">${im.caption?`<figcaption>${esc(im.caption)}</figcaption>`:''}</figure>`).join('')}</div>`}
const footer=(dark=false)=>`<footer class="v9-footer ${dark?'dark':''}">${H('approver')?`<span>الاعتماد <b>${esc(V('approver'))}</b></span>`:'<span></span>'}${stamp()}</footer>`;
function density(){let s=lines(V('goals')).length+lines(V('execution')).length+lines(V('recommendations')).length+metricData().length+photos().length;return s<11?'light':s<22?'medium':'dense'}

// 1 — institutional wave report
function ReportTemplateOne(){return `<article class="v9-sheet ref-one ${density()}"><div class="one-wave top"></div><header>${ident()}${stamp()}</header><section class="one-title"><small>${esc(V('reportType')||'تقرير برنامج')}</small><h1>${esc(title())}</h1>${person()}</section>${factStrip('one-facts')}<main><div class="one-grid"><section class="one-goal"><h2>الهدف العام</h2>${p('generalGoal')}</section>${H('goals')?`<section class="one-objectives"><h2>الأهداف</h2><div>${bullet(V('goals'))}</div></section>`:''}</div>${metricData().length?`<section class="one-metrics"><h2>المؤشرات والنتائج</h2>${kpiRow('one-kpis')}</section>`:''}<div class="one-lower">${H('results')?`<section><h2>أثر البرنامج</h2>${p('results')}</section>`:''}${H('recommendations')?`<section><h2>التوصيات</h2>${bullet(V('recommendations'),'plain')}</section>`:''}</div>${photos().length?`<section class="one-evidence"><h2>الشواهد والصور</h2>${gallery('one-gallery')}</section>`:''}</main><div class="one-wave bottom"></div>${footer(true)}</article>`}

// 2 — performance card / blue KPI reference
function ReportTemplateTwo(){return `<article class="v9-sheet ref-two ${density()}"><header class="two-head">${ident()}<div><small>${esc(V('reportType')||'تقرير أداء')}</small><h1>${esc(title())}</h1></div>${stamp()}</header><section class="two-band">${kpiRow('two-topkpi')}</section><main class="two-main"><div class="two-split"><section class="two-chart"><h2>مؤشرات الأداء الرئيسية</h2>${rings('two-rings')}</section>${H('goals')?`<section class="two-goals"><h2>الأهداف الرئيسية</h2>${bullet(V('goals'),'check')}</section>`:''}</div><div class="two-split second">${H('execution')?`<section class="two-exec"><h2>تفاصيل التنفيذ</h2>${lines(V('execution')).map((x,i)=>`<div class="bar"><span>${esc(x)}</span><i style="--w:${Math.max(35,90-i*8)}%"></i></div>`).join('')}</section>`:''}${H('results')?`<section class="two-results"><h2>أبرز النتائج</h2>${p('results')}</section>`:''}</div>${H('recommendations')?`<section class="two-recs"><h2>التوصيات</h2>${bullet(V('recommendations'),'check')}</section>`:''}${photos().length?`<section class="two-evidence"><h2>الشواهد والصور</h2>${gallery('two-gallery')}</section>`:''}</main>${footer(true)}</article>`}

// 3 — editorial purple with image + quote reference
function ReportTemplateThree(){return `<article class="v9-sheet ref-three ${density()}"><div class="three-dots"></div><header>${ident()}${stamp()}</header><section class="three-title"><small>${esc(V('reportType')||'تقرير تعليمي')}</small><h1>${esc(title())}</h1><p>${H('generalGoal')?esc(V('generalGoal')).slice(0,150):''}</p>${person()}</section>${factStrip('three-facts')}<main><section class="three-feature">${photos().length?`<div class="three-photo">${gallery('three-hero-photo')}</div>`:''}<div class="three-quote"><span>“</span><h2>الهدف</h2>${p('generalGoal')}</div></section>${H('goals')?`<section class="three-objectives"><h2>الأهداف التفصيلية</h2><div>${bullet(V('goals'),'pill')}</div></section>`:''}<div class="three-bottom"><section>${H('execution')?`<h2>أبرز التنفيذ</h2>${p('execution')}`:''}</section><section>${rings('three-rings')}</section></div>${H('results')?`<section class="three-impact"><h2>الأثر والنتائج</h2>${p('results')}</section>`:''}${photos().length>1?`<section class="three-gallery-wrap"><h2>الشواهد المصورة</h2>${gallery('three-gallery')}</section>`:''}</main>${footer(true)}</article>`}

// 4 — vertical numbered journey reference
function ReportTemplateFour(){const stages=[];if(H('generalGoal'))stages.push(['الهدف',V('generalGoal')]);if(H('execution'))lines(V('execution')).forEach((x,i)=>stages.push([i===0?'التنفيذ':'مرحلة التنفيذ',x]));if(H('results'))stages.push(['النتائج',V('results')]);if(H('recommendations'))stages.push(['التوصيات',lines(V('recommendations')).join(' • ')]);return `<article class="v9-sheet ref-four ${density()}"><header>${ident()}${stamp()}</header><section class="four-title"><div><small>${esc(V('reportType')||'برنامج / مبادرة / فعالية')}</small><h1>${esc(title())}</h1>${person()}</div><aside><h3>أبرز المؤشرات</h3>${rings('four-side-rings')}</aside></section>${factStrip('four-facts')}<main class="four-layout"><section class="four-path">${stages.slice(0,6).map((s,i)=>`<div class="four-step s${i}"><div class="num">${String(i+1).padStart(2,'0')}</div><div><h2>${esc(s[0])}</h2><p>${esc(s[1])}</p></div></div>`).join('')}</section><aside class="four-side">${H('goals')?`<section><h2>الأهداف</h2>${bullet(V('goals'),'mini')}</section>`:''}${kpiRow('four-kpis')}</aside></main>${photos().length?`<section class="four-photos"><h2>الشواهد والصور</h2>${gallery('four-gallery')}</section>`:''}${footer(true)}</article>`}

// 5 — teal educational flow reference
function ReportTemplateFive(){return `<article class="v9-sheet ref-five ${density()}"><div class="five-lines"></div><header>${ident()}${stamp()}</header><section class="five-title"><small>${esc(V('reportType')||'تقرير تعليمي')}</small><h1>${esc(title())}</h1><p>${H('generalGoal')?esc(V('generalGoal')).slice(0,130):''}</p>${person()}</section>${factStrip('five-facts')}<main><section class="five-flow"><div class="five-goal"><div class="target">◎</div><h2>الهدف العام</h2>${p('generalGoal')}</div>${H('goals')?`<div class="five-goals"><h2>الأهداف التفصيلية</h2>${bullet(V('goals'),'line')}</div>`:''}</section>${metricData().length?`<section class="five-metrics"><h2>أبرز المؤشرات</h2>${rings('five-rings')}${kpiRow('five-kpis')}</section>`:''}<div class="five-content">${H('execution')?`<section><h2>آلية التنفيذ</h2>${bullet(V('execution'),'soft')}</section>`:''}${H('results')?`<section><h2>الأثر</h2>${p('results')}</section>`:''}</div>${photos().length?`<section class="five-evidence"><h2>الشواهد والصور</h2>${gallery('five-gallery')}</section>`:''}</main>${footer(true)}</article>`}

const REG={aurora:ReportTemplateOne,editorial:ReportTemplateTwo,minimal:ReportTemplateThree,prism:ReportTemplateFour,impact:ReportTemplateFive};
function fit(){const s=q('.v9-sheet');if(!s)return;s.style.setProperty('--fit',1);requestAnimationFrame(()=>{const h=s.scrollHeight;if(h>1123){const z=Math.max(.74,1123/h);s.style.setProperty('--fit',z.toFixed(3));s.classList.toggle('auto-dense',z<.9)}})}
window.render=function(){const prev=q('#reportPreview');if(!prev)return;const key=F.elements.theme?.value||'aurora';prev.className=`report v9-report theme-${key}`;prev.style.transform=`scale(${typeof zoom!=='undefined'?zoom:.72})`;prev.innerHTML=(REG[key]||ReportTemplateOne)();const z=q('#zoomText');if(z)z.textContent=Math.round((typeof zoom!=='undefined'?zoom:.72)*100)+'%';fit()};
const names={aurora:['النموذج المؤسسي','موجات رسمية خضراء وتقسيمات تعليمية متوازنة'],editorial:['بطاقة المؤشرات','مؤشرات أداء ورسوم قياس بتكوين أزرق احترافي'],minimal:['التقرير التحريري','تكوين تحريري بصري مع صورة واقتباس ومؤشرات'],prism:['قيادة وأثر','رحلة مرقمة ملونة تربط الهدف بالتنفيذ والنتائج'],impact:['التدفق التعليمي','تدفق بصري تركوازي للأهداف والمؤشرات والشواهد']};
Object.entries(names).forEach(([k,[a,b]])=>{const c=q(`input[name="theme"][value="${k}"]`)?.closest('.theme-card');if(c){const t=c.querySelector('strong'),s=c.querySelector('span');if(t)t.textContent=a;if(s)s.textContent=b;c.dataset.v9=k}});
const badge=q('.side-intro .eyebrow');if(badge)badge.textContent='V9';document.title='توثيق — صانع التقارير الذكي V9';
F.addEventListener('input',()=>requestAnimationFrame(window.render));F.addEventListener('change',()=>requestAnimationFrame(window.render));
document.addEventListener('click',e=>{const card=e.target.closest('.theme-card');if(card){const r=card.querySelector('input[type=radio]');if(r&&!r.checked){r.checked=true;r.dispatchEvent(new Event('change',{bubbles:true}))}}});
setTimeout(window.render,80);
})();